import { NextRequest, NextResponse } from "next/server";
import { openrouter } from "@/config/openrouter";
import { db } from "@/config/db";
import { ScreenConfigTable } from "@/config/schema";
import { and, eq } from "drizzle-orm";
import { currentUser } from "@clerk/nextjs/server";


export async function POST(req: NextRequest) {
    const { projectId, screenId, oldCode, userInput } = await req.json();
    const user = await currentUser();
    const email = user?.primaryEmailAddress?.emailAddress;
    if (!user || !email) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (!projectId || !screenId || !userInput) {
      return NextResponse.json(
        { error: "Invalid request payload: missing projectId, screenId, or userInput" },
        { status: 400 }
      );
    }
    const USER_INPUT = `
        ${oldCode} + Make as per user input, keeping design, structure and styling the same, do not change it.
        Make only the changes requested by the user, do not change the design, structure and styling.
        User input: ${userInput}
    `

    try {
        const aiResponse = await openrouter.chat.send({
          chatRequest: {
            model: "google/gemini-2.5-flash",
            messages: [
              {
                role: "user",
                content: [
                  {
                    type: "text",
                    text: USER_INPUT + "Output HTML ONLY" + "NO markdown, NO comments, NO explanations",
                  },
                ],
              },
              
            ],
            stream: false,
          },
        });
      
        const code = aiResponse.choices[0]?.message?.content
        if (!code) {
          return NextResponse.json({ error: 'No content generated by AI: code is empty' }, { status: 500 });
        }
        const updateResult = await db.update(ScreenConfigTable).set({
          code: code as string,
        }).where(and(eq(ScreenConfigTable.projectId, projectId as string), eq(ScreenConfigTable.screenId, screenId as string)))
        .returning();

        if (!updateResult.length) {
          return NextResponse.json({ error: 'Screen not found' }, { status: 404 })
        }
      
        return NextResponse.json(updateResult[0]);
      } catch (error) {
        console.error('Failed to generate screen UI', error);
        return NextResponse.json({ error: 'Failed to generate screen UI, Internal Server Error' }, { status: 500 });
      }
}